# Generated by Django 4.0.6 on 2022-09-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='image',
            new_name='venue_image',
        ),
    ]
