# Generated by Django 4.0.6 on 2022-09-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubUser',
        ),
    ]
