# Generated by Django 4.0.6 on 2022-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
